[package]
name = "agent4linn"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
serde = "1.0.228"
serde_json = "1.0.145"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
wasmer = "6.1.0"
wasmer-types = "6.1.0"
wasmer-wasix = "0.601.0"
